GET http://localhost:5050/skyPost/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNpTW9aOSIsImVtYWlsIjoic2ltb25lam9uYXMwOEBnbWFpbC5jb20iLCJfaWQiOiI2NTNiZDgzYmEyMDQwZTUwODQ5ZTI4YjciLCJpYXQiOjE2OTg0MjA3OTksImV4cCI6MTY5ODY3OTk5OX0.evuIKYcFUxzW_kS3usumdZ20T8QiAkZUc4CC4A0Zhek

###
POST http://localhost:5050/skyPost/post HTTP/1.1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNpTW9aOSIsImVtYWlsIjoic2ltb25lam9uYXMwOEBnbWFpbC5jb20iLCJfaWQiOiI2NTNiZjViODY0NDYwZWRiYzJmYjYyZTkiLCJpYXQiOjE2OTg3NjI3MjAsImV4cCI6MTY5OTAyMTkyMH0.-EnJmvcs8OEuPIqFV-6PT4bwnHPu3VDKlbVHIaTkMsE
Content-Type: application/json

{
  "object": "NGC6986",
  "title": "NGC6986 HOO",
  "description": {
    "instrumentation": {
      "telescope": "SkyWatcher P400"
    },
    "place": {
      "coordinates": {
        "latitude": 48.887,
        "longitude": 12.231
      }
    }
  }
}

###
GET http://localhost:5050/skyPost/6548d65e037e169293a3e010
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNpTW9aOSIsImVtYWlsIjoic2ltb25lam9uYXMwOEBnbWFpbC5jb20iLCJfaWQiOiI2NTNiZjViODY0NDYwZWRiYzJmYjYyZTkiLCJpYXQiOjE2OTkyNjgzODIsImV4cCI6MTY5OTUyNzU4Mn0.ef7huDo7YzQEOPE0gWpIiy13zH7XTDu7RUsTAwcasJI


###
GET http://localhost:5051/skyPost/account/posts/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNpTW9aOSIsImVtYWlsIjoic2ltb25lam9uYXMwOEBnbWFpbC5jb20iLCJfaWQiOiI2NTRlNjI4YzNjOTc0NjlmMzQyNGYxZTYiLCJpYXQiOjE2OTk2MzU4ODIsImV4cCI6MTY5OTg5NTA4Mn0.l7aI6cynHZFM9UdDg3MxjdUsomCI0N_l-X2bz6HLUCo
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNpTW9aOSIsImVtYWlsIjoic2ltb25lam9uYXMwOEBnbWFpbC5jb20iLCJfaWQiOiI2NTRlNjI4YzNjOTc0NjlmMzQyNGYxZTYiLCJpYXQiOjE2OTk2MzU4ODIsImV4cCI6MTY5OTg5NTA4Mn0.l7aI6cynHZFM9UdDg3MxjdUsomCI0N_l-X2bz6HLUCo


###
GET http://localhost:5051/skyPost/userPost/654f41e45147900c39383e29
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkVyaWNhUG9scGV0dG9uYSIsImVtYWlsIjoiZXJpY2Eucm9uY2lAZ21haWwuY29tIiwiX2lkIjoiNjU0ZjQxZTQ1MTQ3OTAwYzM5MzgzZTI5IiwiaWF0IjoxNjk5NjkzMDU3LCJleHAiOjE2OTk5NTIyNTd9.ERN2EUuaetwZLEtoYAV0tW7Roa2lbSNP7N-Hbj7X_UM